### ISSUE TITLE
Filebeat on “Docker for AWS” fails to start

### ISSUE THREAD

**Issue by shazChaudhry** [shazChaudhry/elastic#11]
Issue has been logged on filebeat discussion board - https://discuss.elastic.co/t/filebeat-on-docker-for-aws-fails-to-start/110345

solutions mentioned in https://github.com/docker/for-aws/issues/123 has not worked in my case and filebeat is unable to locate /var/lib/docker/containers/ path. The error I get is:
>"invalid mount config for type "bind": bind source path does not exist"

**Comment by adrissss** [comment]
Filebeat is working for me in a "docker for aws" swarm cluster with this configuration for the filebeat service (notice that I had to change the user to root for filebeat containers, and that I mount host's directories in /host_docker in the container):

```
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.0.0-rc1
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
    environment:
      LOGSTASH_HOST: my_logstash_host
      LOGSTASH_PORT: my_logstash_port
      SHIPPER_NAME: my_swarm_name
    user: root
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.yml
    deploy:
      mode: global

configs:
  filebeat_config:
    file: ./config_files/filebeat_config.yml
```
additionally, my filebeat_config.yml file (providing java stack trace multiline detection inside the docker json log format) is :

```
filebeat:
  prospectors:
    - type: log
      paths:
        - '/host_docker/var/lib/docker/containers/*/*.log'
      json.message_key: log
      json.add_error_key: true
      multiline:
        pattern: "^\t|^[[:space:]]+(at|...)|^Caused by:"
        match: after
      processors:
        - add_docker_metadata:
            host: "unix:///host_docker/docker.sock"
            match_source_index: 5
output:
  logstash:
    hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT}"]
shipper:
  name: "${SHIPPER_NAME}"
logging:
  files:
    rotateeverybytes: 10485760 # = 10MB
  level: info
```
