### ISSUE TITLE
Configure filebeat to fetch from local filesystem

### ISSUE THREAD

**Issue by lewismc** [shazChaudhry/elastic#44]
I am running a non-containerized application locally which produces timeseries logs in a text file (in addition to executing other application functionality). I wanted to containerize all of the ELK stack for analyzing the timeseries logs so this project is just what I needed. I then wanted to use filebeat to feed the local log4j text log to logstash and into Elasticsearch.

Having deployed everything as follows
```
$ docker stack services elastic
ID                  NAME                     MODE                REPLICAS            IMAGE                                                 PORTS
hwv9mjnnbady        elastic_kibana           replicated          1/1                 docker.elastic.co/kibana/kibana:7.9.1
k2yjhizxkcdd        elastic_logstash         replicated          1/1                 docker.elastic.co/logstash/logstash:7.9.1             *:12201->12201/udp
m3xqajcqmopx        elastic_swarm-listener   replicated          1/1                 dockerflow/docker-flow-swarm-listener:latest
vuvk78117tmj        elastic_elasticsearch    global              1/1                 docker.elastic.co/elasticsearch/elasticsearch:7.9.1
y76njf0lta3q        elastic_apm-server       replicated          1/1                 docker.elastic.co/apm/apm-server:7.9.1
yl3f8ha2frzt        elastic_proxy            replicated          2/2                 dockerflow/docker-flow-proxy:latest                   *:80->80/tcp, *:443->443/tcp, *:8200->8200/tcp, *:9200->9200/tcp
```
and then filebeat
```
docker stack services filebeat
ID                  NAME                MODE                REPLICAS            IMAGE                                    PORTS
51di10aflys8        filebeat_filebeat   global              1/1                 docker.elastic.co/beats/filebeat:7.9.1
```
The problem I am having is configuring the application log directory for filebeat to fetch. For example, my logs are written to `/Users/$name/some/directory/application.log`.

Can you please advise as to how I configure [filebeat-docker-compose.yml](https://github.com/shazChaudhry/docker-elastic/blob/master/filebeat-docker-compose.yml) to pick up the local logs?

Thanks in advance.

**Comment by shazChaudhry** [comment]
Hi @lewismc 

I am very pleased to hear you find this repo useful :)

Sending non-containerized application logs to elasticsearch is sttraight forward. Please see the compose and configuration files below

1) Mount your application log directory via volumes in filebeat compose file

```
version: "3.8"
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION:-7.9.1}
    hostname: "{{.Node.Hostname}}-filebeat"
    user: root
    networks:
      - elastic
    configs:
      - source: fb_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - filebeat:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - /Users/$name/some/directory:/tmp/logs:ro # Mount your application log directory
      - /var/log/:/var/log/:ro
      - /var/log/audit/:/var/log/audit/:ro
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-node1}
      - KIBANA_HOST=${KIBANA_HOST:-node1}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    command: ["--strict.perms=false"]
    deploy:
      mode: global
networks:
  elastic:
    external: true
    name: host
volumes:
  filebeat:
configs:
  fb_config:
    file: $PWD/elk/beats/filebeat/config/filebeat.yml
```

2)  Configure [filebeat.inputs](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html) of type log in filebeat.yml
```
filebeat.modules:
- module: system
  syslog:
    enabled: true
  auth:
    enabled: true
- module: auditd
  log:
    enabled: true

filebeat.inputs:
- type: log
  enabled: true
  paths:
   - /tmp/logs/*.log
  stream: all 

#========================== Filebeat autodiscover ==============================
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

#================================ Processors ===================================
processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~
- add_locale:
    format: offset
- add_host_metadata:
    netinfo.enabled: true

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}:9200"]
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

#============================== Dashboards =====================================
setup.dashboards:
  enabled: true

#============================== Kibana =========================================
setup.kibana:
  host: "${KIBANA_HOST}:80"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

#============================== Xpack Monitoring ===============================
xpack.monitoring:
  enabled: true
  elasticsearch:
```

I have just tested the above configuration in a vagrantbox envrionment and it works. Please do let me know if you need further help on this

Regards,
Shahzad
